---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentDependencies:
  aws.greengrass.StreamManager:
    VersionRequirement: ^2.0.0
  aws.greengrass.ShadowManager:
    VersionRequirement: ^2.0.0
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ShadowManager:
        "com.example.opc-archiver:shadow:1":
          operations:
            - "aws.greengrass#GetThingShadow"
            - "aws.greengrass#UpdateThingShadow"
          resources:
            - "*"
        "com.example.opc-archiver:shadow:2":
          operations:
            - "aws.greengrass#ListNamedShadowsForThing"
          resources:
            - "{iot:thingName}"
    Bucket: "CDK.DEST_BUCKET_NAME" # destination bucket
    OpcStreamName: "opc_archiver_stream" # OPC stream name written from SiteWise
    LogLevel: "info" # Log level (debug, info, warn, error, critical)
Manifests:
  - Platform:
      os: linux
    Lifecycle:
      Install:
        Timeout: 300
        Script: python3 -m pip --timeout=120 install -v -r {artifacts:decompressedPath}/opc-archiver/requirements.txt
      Run:
        Script: "python3 -u {artifacts:decompressedPath}/opc-archiver/src/main.py"
    Artifacts:
      - URI: s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/opc-archiver.zip
        Unarchive: "ZIP"
  - Platform:
      os: windows
    Lifecycle:
      Install:
        Timeout: 300
        Script: python -m pip --timeout=120 install -v -r {artifacts:decompressedPath}/opc-archiver/requirements.txt
      Run:
        Script: "python -u {artifacts:decompressedPath}/opc-archiver/src/main.py"
    Artifacts:
      - URI: s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/opc-archiver.zip
        Unarchive: "ZIP"
