name: Synth
on:
  pull_request:
    branches: ["main"]
jobs:
  cdk-synth:
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT_ID: "123456789012"
      AWS_REGION: "us-west-2"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: |
          cd cdk
          npm ci
          npx cdk synth --all
